In [1]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy
import tensorflow as tf

In [2]:
seed = 0
numpy.random.seed(seed)
tf.random.set_seed(3)

In [3]:
df=pd.read_csv('./dataset/sonar.csv', header=None)

In [4]:
dataset = df.values

In [5]:
x=dataset[:,0:60].astype(float)

In [7]:
y_obj=dataset[:,60]

In [8]:
e=LabelEncoder()
e.fit(y_obj)

LabelEncoder()

In [9]:
y=e.transform(y_obj)

In [10]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=seed)

In [12]:
x_train, x_test

(array([[0.0135, 0.0045, 0.0051, ..., 0.0028, 0.003 , 0.003 ],
        [0.0293, 0.0644, 0.039 , ..., 0.016 , 0.0095, 0.0011],
        [0.024 , 0.0218, 0.0324, ..., 0.0019, 0.0066, 0.0023],
        ...,
        [0.0228, 0.0106, 0.013 , ..., 0.0045, 0.0063, 0.0039],
        [0.0373, 0.0281, 0.0232, ..., 0.0054, 0.0085, 0.006 ],
        [0.018 , 0.0444, 0.0476, ..., 0.005 , 0.0073, 0.0022]]),
 array([[0.0079, 0.0086, 0.0055, ..., 0.0058, 0.0059, 0.0032],
        [0.0229, 0.0369, 0.004 , ..., 0.0029, 0.0104, 0.0163],
        [0.0442, 0.0477, 0.0049, ..., 0.0105, 0.0059, 0.0105],
        ...,
        [0.0315, 0.0252, 0.0167, ..., 0.0035, 0.0001, 0.0055],
        [0.0428, 0.0555, 0.0708, ..., 0.0084, 0.0113, 0.0049],
        [0.0239, 0.0189, 0.0466, ..., 0.0026, 0.0036, 0.0024]]))

In [13]:
y_train, y_test

(array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0]),
 array([1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1]))

In [15]:
model = Sequential()
model.add(Dense(24, input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [16]:
model.compile(loss='mean_squared_error',
             optimizer='adam',
             metrics=['accuracy'])

In [17]:
model.fit(x_train, y_train, epochs=130, batch_size=5)

Epoch 1/130
29/29 [==============================] - 0s 499us/step - loss: 0.2468 - accuracy: 0.4837
Epoch 2/130
29/29 [==============================] - 0s 463us/step - loss: 0.2384 - accuracy: 0.6013
Epoch 3/130
29/29 [==============================] - 0s 463us/step - loss: 0.2153 - accuracy: 0.6879
Epoch 4/130
29/29 [==============================] - 0s 463us/step - loss: 0.2156 - accuracy: 0.7034
Epoch 5/130
29/29 [==============================] - 0s 463us/step - loss: 0.1945 - accuracy: 0.7643
Epoch 6/130
29/29 [==============================] - 0s 463us/step - loss: 0.1900 - accuracy: 0.7571
Epoch 7/130
29/29 [==============================] - 0s 427us/step - loss: 0.1884 - accuracy: 0.7188
Epoch 8/130
29/29 [==============================] - 0s 463us/step - loss: 0.1708 - accuracy: 0.8209
Epoch 9/130
29/29 [==============================] - 0s 463us/step - loss: 0.1602 - accuracy: 0.7874
Epoch 10/130
29/29 [==============================] - 0s 463us/step - loss: 0.1594 - accura

In [18]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.1447 - accuracy: 0.8571


[0.14466208219528198, 0.8571428656578064]

In [19]:
model.save('my_model.h5')

In [20]:
from keras.models import load_model

In [21]:
m1 = load_model('my_model.h5')

In [22]:
m1.evaluate(x_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.1447 - accuracy: 0.8571


[0.14466208219528198, 0.8571428656578064]